import	ala_demoniaca	from	'../assets/monsters/Ala_Demoniaca.jpg'
import	cerbero_di_fuoco	from	'../assets/monsters/Cerbero_di_Fuoco.jpg'
import	serpente_velenoso	from	'../assets/monsters/Serpente_Velenoso.jpg'
import	scheletro_arciere	from	'../assets/monsters/Scheletro_Arciere.jpg'
import	strega	from	'../assets/monsters/Strega.jpg'
import	spirito	from	'../assets/monsters/Spirito.jpg'
import	uomo_bestia	from	'../assets/monsters/Uomo_Bestia.jpg'
import	folletto	from	'../assets/monsters/Folletto.jpg'
import	goblin	from	'../assets/monsters/Goblin.jpg'
import	ragno_gigante	from	'../assets/monsters/Ragno_Gigante.jpg'
import	grendel	from	'../assets/monsters/Grendel.jpg'
import	centauro	from	'../assets/monsters/Centauro.jpg'
import	stregone	from	'../assets/monsters/Stregone.jpg'
import	mago_oscuro	from	'../assets/monsters/Mago_Oscuro.jpg'
import	succube	from	'../assets/monsters/Succube.jpg'
import	mago_bianco	from	'../assets/monsters/Mago_Bianco.jpg'
import	assassino_silvano	from	'../assets/monsters/Assassino_Silvano.jpg'
import	minotauro	from	'../assets/monsters/Minotauro.jpg'
import	manticora	from	'../assets/monsters/Manticora.jpg'
import	idra	from	'../assets/monsters/Idra.jpg'
import	behemoth	from	'../assets/monsters/Behemoth.jpg'
import	chimera	from	'../assets/monsters/Chimera.jpg'
import	golem	from	'../assets/monsters/Golem.jpg'
import	lich	from	'../assets/monsters/Lich.jpg'
import	ogre	from	'../assets/monsters/Ogre.jpg'
import	troll	from	'../assets/monsters/Troll.jpg'
import	jotun	from	'../assets/monsters/Jotun.jpg'
import	drago	from	'../assets/monsters/Drago.jpg'
import	demone	from	'../assets/monsters/Demone.jpg'
import	ciclope	from	'../assets/monsters/Ciclope.jpg'

// BOSS
import	re_bestia	from	'../assets/monsters/Re_Bestia.jpg'
import	genitrice_dei_folletti	from	'../assets/monsters/Genitrice_dei_Folletti.jpg'
import	uruk	from	'../assets/monsters/Uruk.jpg'
import	goliath	from	'../assets/monsters/Goliath.jpg'
import	muro_d_ossa	from	'../assets/monsters/Muro_d\'ossa.jpg'
import	sarith	from	'../assets/monsters/Sarith.jpg'
import	chimera_illusionista	from	'../assets/monsters/Chimera_Illusionista.jpg'
import	nameless	from	'../assets/monsters/Nameless.jpg'
import	ragno_titanico	from	'../assets/monsters/Ragno_Titanico.jpg'
import	cuore_del_ragno	from	'../assets/monsters/Cuore_del_Ragno.jpg'
import	idra_regina	from	'../assets/monsters/Idra_Regina.jpg'
import	grendel_degli_abissi	from	'../assets/monsters/Grendel_degli_Abissi.jpg'
import	drago_millenario	from	'../assets/monsters/Drago_Millenario.jpg'
import	gusadt_terodn	from	'../assets/monsters/Gusadt-Terodn.jpg'
import	garkar	from	'../assets/monsters/Garkar.jpg'
import	hurian	from	'../assets/monsters/Hurian.jpg'
import	nar_xarn	from	'../assets/monsters/Nar\'Xarn.jpg'
import	khun	from	'../assets/monsters/Khun.jpg'
import	yarangur	from	'../assets/monsters/Yarangur.jpg'



const monstersList = {
  monsters:{
    'monster-1': {id: 'monster-1', type: 'beast', label:	'Ala Demoniaca'	, image:	ala_demoniaca, description: 'Una creatura dall’aspetto orribile, frenetica e affamata. Non occupando una posizione di riguardo nella catena alimentare deve spesso accontentarsi degli scarti delle altre creature. Le ali che usa per accecare i suoi nemici sono esili e non le consentono di volare per un lungo periodo di tempo.' },
    'monster-2': {id: 'monster-2', type: 'beast', label:	'Cerbero di Fuoco'	, image:	cerbero_di_fuoco, description: 'Una bestia a tre teste, ognuna nervosa e rumorosa allo stesso modo. È una creatura sempre irata, litiga perfino con sé stessa: spesso si vedono le teste litigare per il cibo. In grado di produrre piccole fiammate con le bocca rappresentano una minaccia soprattutto per le creature più lente.' },
    'monster-3': {id: 'monster-3', type: 'beast', label:	'Serpente Velenoso'	, image:	serpente_velenoso, description: 'Un viscido serpente dagli occhi verde acceso, schivo e prudente. Quasi mai attacca per primo e preferisce vivere in quiete, quando viene attaccato però si difende usando il suo potente veleno. Il suo sonaglio è un incubo dei piccoli roditori della sua zona: sentirlo provoca in questi una reazione di panico.' },
    'monster-4': {id: 'monster-4', type: 'magical', label:	'Scheletro Arciere'	, image:	scheletro_arciere, description: 'Incubo di ogni visitatore dei cimiteri, per nulla simpatico. Si diverte a tormentare tutti coloro che fanno visita ai loro cari oltre l’ora del tramonto, con il suo arco scaglia frecce velenose in grado di intossicare ed uccidere le sue vittime. Non può abbandonare il cimitero del regno perché le sue ossa tornerebbero inanimate e finirebbe tutto il divertimento.' },
    'monster-5': {id: 'monster-5', type: 'magical', label:	'Strega'	, image:	strega, description: 'Creatura magica dall’aspetto gradevole, si rivela spietata se occorre. All’apparenza una ragazza normale, questa malignità nasconde capacità di ipnosi e manipolazione delle sue vittime. Le storie raccontate ai bambini del regno narrano delle sue capacità di rapire i sogni degli impuri e, in casi rari, di impossessarsi dei loro corpi per lungo tempo.' },
    'monster-6': {id: 'monster-6', type: 'magical', label:	'Spirito '	, image:	spirito, description: 'Anima in pena, senza speranza di redenzione. Passa le sue giornate a vagare senza meta, non rappresenta una reale minaccia per nessuno. Le uniche sue vittime sono gli avventurieri che, incrociandolo durante delle esplorazioni, muoiono di crepacuore o finiscono in qualche dirupo fuggendo.' },
    'monster-7': {id: 'monster-7', type:'humanoid', label:	'Uomo Bestia'	, image:	uomo_bestia, description: 'Un umanoide dall’indole mansueta, spinto solo dalla fame. Solitamente dorme per la maggior parte della sua giornata, si sveglia per cercare cibo e acqua. La sua muscolatura sviluppata gli consente di intimorire tutte le altre creature, costrette a lasciargli le prede più succulente ed accontentarsi degli scarti.' },
    'monster-8': {id: 'monster-8', type:'humanoid', label:	'Folletto'	, image:	folletto, description: 'Piccolo essere dalle fattezze esili, fastidioso e irriverente. Si diverte a rovinare raccolti, far fuggire il bestiame e sabotare opere come mulini o pozzi d’acqua. Una volta scoperto fugge via rapidamente e senza lasciare tracce: difficilmente ingaggia uno scontro con qualcuno, conscio del fatto che potrebbe lasciarci la pelle.' },
    'monster-9': {id: 'monster-9', type:'humanoid', label:	'Goblin'	, image:	goblin, description: 'Umanoide spigoloso, furbo ed agile. Accompagnato sempre dal suo fido pugnale, si guadagna da mangiare schivando i problemi e ricorrendo alla sua notevole arguzia. Difficilmente lo si incontra in un gruppo numeroso, ancor più raro incontrarlo a banchettare con altre razze di mostri.' },
    'monster-10': {id: 'monster-10', type: 'beast', label:	'Ragno Gigante'	, image:	ragno_gigante, description: 'Pelosa bestia con 6 occhi scuri, goffa e lurida. Attraverso ghiandole poste sotto la bocca spruzza veleno molto potente, in grado di abbattere anche bestie più imponenti di lui. Le sue prede finiscono intorpidite e vengono mangiate ancora vive, non esiste modo per sfuggire alla morsa delle sue fauci.' },
    'monster-11': {id: 'monster-11', type: 'beast', label:	'Grendel'	, image:	grendel, description: 'Una bestia con lunghi artigli, molto feroce. La sua rapidità sorprende anche le creature più spavalde, la sua ferocia non è seconda a quella di nessun altro e il suo desiderio di sangue lo rende insaziabile. Finire nelle sue mire è altamente sconsigliato, molto spesso le sue vittime non si accorgono nemmeno di essere la sua preda.' },
    'monster-12': {id: 'monster-12', type: 'beast', label:	'Centauro'	, image:	centauro, description: 'Elegante creatura mezzo uomo e mezzo cavallo. Dotato di una mira infallibile, spesso cacciano in gruppi di 3 o più esemplari per sfidarsi a chi riesce ad uccidere la preda più impegnativa. Le storie raccontano che mai nessuna preda sia sfuggita alla precisione del suo arco, l’unico modo per uscire vivi da uno scontro è affrontarlo prima di essere colpiti.' },
    'monster-13': {id: 'monster-13', type: 'magical', label:	'Stregone'	, image:	stregone, description: 'Una creatura magica, dall’aspetto elegante e fiero. La varietà di magie conosciute lo rende pericoloso per tutti, con la capacità di dominare le fiamme riesce anche a mettere in fuga eventuali avversari che sa di non poter sconfiggere. Sempre alla ricerca di nuove tecniche da imparare, viaggia in solitaria per sete di conoscenza e di potere.' },
    'monster-14': {id: 'monster-14', type: 'magical', label:	'Mago Oscuro'	, image:	mago_oscuro, description: 'Un mago in possesso di ampia conoscenza delle arti oscure, cupo e solitario. Le sue competenze sono così avanzate che spesso uccide le sue prede con il solo terrore che instilla nelle loro menti. Giocare con le arti oscure lo rende privo di gioia e il suo unico motivo di vita è imparare altre magie per torturare le sue vittime.' },
    'monster-15': {id: 'monster-15', type: 'magical', label:	'Succube'	, image:	succube, description: 'Creatura magica di bell’aspetto e accomodante. Il legame con il suo padrone demone è indissolubile e non conosce una vita senza di esso. La sua abilità di tentare gli uomini deriva sia dalla sua bellezza che dalla sua capacità di manipolarne le menti: quasi sempre esegue gli ordini del suo padrone e non agisce di sua spontanea volontà.' },
    'monster-16': {id: 'monster-16', type:'humanoid', label:	'Mago Bianco'	, image:	mago_bianco, description: 'Benevola creatura dal carattere gentile e disponibile. Passa le sue giornate a raccogliere erbe per i sui intrugli curativi per poi sperimentarli su mostri malati e morenti. Difficilmente lo si vede impegnato in scontri con altre creature, sia perché queste ultime lo rispettano come alleato, sia perché la sua estrema magrezza lo rende una preda poco appetibile per chiunque.' },
    'monster-17': {id: 'monster-17', type:'humanoid', label:	'Assassino Silvano'	, image:	assassino_silvano, description: 'Misterioso umano col volto coperto da un mantello verde, furtivo ed agile. Il suo carattere solitario lo porta a non avere amici, vaga per il regno in cerca di nuove sfide che possano metterlo alla prova. Il suo fidato coltello a due lame è un’arma molto pericolosa perfino per i mostri più corazzati, lo affila continuamente e lo tempra con le fiamme dei bracieri.' },
    'monster-18': {id: 'monster-18', type:'humanoid', label:	'Minotauro'	, image:	minotauro, description: 'Mezzo umano e mezzo toro, irascibile e permaloso. Sempre pronto alla battaglia, riesce a non farsi sorprendere nemmeno durante il sonno. La sua pelle è dura come la roccia e può resistere anche ad attacchi sferrati con lame o pugnali di piccole dimensioni. Data la sua mole e la sua tenacia è molto difficile avere la meglio in uno scontro, per questo motivo ogni cacciatore che si rispetti possiede un suo scalpo nella sua sala dei trofei.' },
    'monster-19': {id: 'monster-19', type: 'beast', label:	'Manticora'	, image:	manticora, description: 'Belva dalle sembianze leonine, minacciosa e fiera. È di gran lunga uno dei peggiori incontri che si possa fare nelle terre del regno, aggressiva con chiunque intralci il suo cammino e sempre alla ricerca di cibo. Le leggende che raccontano della sua ferocia sono però confuse e diverse a seconda del villaggio che le racconta: nessuno ha avuto la fortuna di poterle studiare e descriverle dettagliatamente.' },
    'monster-20': {id: 'monster-20', type: 'beast', label:	'Idra'	, image:	idra, description: 'Una bestia enorme, con tre lunghi colli affusolati e tre teste identiche. Data la sua mole non è in grado di spostarsi velocemente ma è dotata di una sorprendente agilità nello sferrare morsi con le enormi fauci. Le storie confermano che uno dei pochi modi per metterla in difficoltà è mettere le teste l’una contro l’altra: i pochi ad esserci riusciti raccontano di aver semplicemente chiesto quale delle tre teste fosse la più valorosa…' },
    'monster-21': {id: 'monster-21', type: 'beast', label:	'Behemoth'	, image:	behemoth, description: 'Un feroce esemplare di belva cornuta, irato dal primo all’ultimo giorno di vita. Dove vive lui non possono esserci altri predatori, uccide e divora chiunque sia commestibile. Nelle storie raccontate nel regno è descritto come una bestia dalla ferocia senza limiti, dalla muscolatura imponente e dalla carnagione olivastra. Dotato di una corsa sorprendentemente fluida provoca notevoli scosse di terremoto al suo passaggio: gli abitanti hanno imparato a riconoscere queste avvisaglie e a nascondere se stessi e il bestiame per non attirarne l’attenzione.' },
    'monster-22': {id: 'monster-22', type: 'magical', label:	'Chimera'	, image:	chimera, description: 'Creatura magica, dalla personalità volubile e imprevedibile. È dotata di poteri incredibili, riesce a vincere gli scontri senza toccare il suo avversario. A seconda di quale delle tre teste sia in comando in quel momento la tattica di combattimento varia, è quindi impossibile prevedere le sue mosse. La coda formata da un enorme serpente è sempre vigile e non riposa mai, sorprendere questa bestia alle spalle è un tentativo inutile.' },
    'monster-23': {id: 'monster-23', type: 'magical', label:	'Golem'	, image:	golem, description: 'Enorme ammasso di pietre, lento sia fisicamente che mentalmente. Quando dorme si mimetizza con le rocce circostanti e risulta invisibile anche all’occhio più attento. La sua indole docile non deve trarre in inganno: una volta provocato è infatti capace di distruggere qualsiasi opera umana senza sforzo e non si fa scrupoli a mietere qualche vittima se ha disturbato il suo sonno. Le sue parti rocciose sono tenute insieme da una magia molto potente che si manifesta con bagliori color zaffiro.' },
    'monster-24': {id: 'monster-24', type: 'magical', label:	'Lich'	, image:	lich, description: 'Signore dei non-morti, non molto socievole. Si presenta nel mondo dei vivi sotto forma di scheletro coperto da un lungo mantello a brandelli di color verde muschio. Il suo bastone magico è descritto nelle leggende come un portale per l’aldilà, sulla cima infatti è presente un rubino che mostra ai malcapitati i loro ultimi istanti prima della morte.' },
    'monster-25': {id: 'monster-25', type:'humanoid', label:	'Ogre'	, image:	ogre, description: 'Feroce e muscoloso umanoide, suscettibile e permaloso. Non ama chi mette in dubbio la sua supremazia sul territorio, è dotato di una grossa e pesantissima mazza con cui schiaccia tutti i suoi avversari. Le storie narrano che con il tempo sviluppi la capacità di curarsi le ferite, cosicché un esemplare adulto sia praticamente imbattibile per un normale essere umano.' },
    'monster-26': {id: 'monster-26', type:'humanoid', label:	'Troll'	, image:	troll, description: 'Grasso gigante dalla carnagione verdastra, calmo e disinvolto. Le leggende lo descrivono come brutto e spaventoso, ma il suo tratto preponderante è l’appetito insaziabile: passa l’intera giornata a mangiare e dormire. Si guadagna il rispetto degli altri mostri con il suo terribile lezzo: questa sua caratteristica non permette a nessun altro di mangiare la sua stessa preda e il risultato è che ingrassa fino a scoppiare.' },
    'monster-27': {id: 'monster-27', type:'humanoid', label:	'Jotun'	, image:	jotun, description: 'Mitologico umanoide aggressivo e possessivo. La sua carnagione ricorda i colori della notte, un blu intenso e lucido allo stesso tempo. Sfrutta questa caratteristica per mimetizzarsi nelle notti buie e senza luna per sfamare la sua sete di distruzione: le leggende narrano che il suo sogno sia quello di sedere tra gli dei e che intende guadagnarselo distruggendo il maggior numero di opere possibile. È in grado di lanciare il suo arpione di bronzo ad enormi distanze e con incredibile precisione: non manca mai il suo bersaglio.' },
    'monster-28': {id: 'monster-28', type: 'beast', label:	'Drago'	, image:	drago, description: 'Il re indiscusso di tutte le bestie, feroce ed aggressivo. Dalle sue fauci si originano fiamme che possono fondere la roccia, i suoi artigli dilaniano anche le armature più resistenti e le enormi ali color rubino gli consentono di librarsi in aria per sferrare assalti dal cielo. Le leggende in materia si sprecano: chi pensa sia immortale, altri ritengono abbia un numero di vite superiore a quelle dei gatti, altri ancora rifiutano di accettare la sua esistenza. Quando esce in cerca di cibo si scatena il pandemonio: interi villaggi finiscono preda delle sue tempeste infuocate.' },
    'monster-29': {id: 'monster-29', type: 'magical', label:	'Demone'	, image:	demone, description: 'Incarnazione del male, spregevole e dannato. La sua figura ricorda un enorme pipistrello, con tre occhi color lava con cui riesce a vedere a diversi chilometri con chiarezza disarmante. La sua mole non lascia trapelare l’agilità senza pari che lo contraddistingue: niente è più rapido, veloce e deciso in tutto il regno dei mostri. È il signore delle arti oscure, con lo schiocco delle dita può maledire i suoi avversari e condannarli ad una morte certa: non esiste cura o rimedio che si può porre alla sua malvagia sentenza.' },
    'monster-30': {id: 'monster-30', type:'humanoid', label:	'Ciclope'	, image:	ciclope, description: 'Micidiale macchina da guerra, potente e spietato. La sua fama lo precede, disintegra castelli con la sua potenza mista a rabbia. Ha una mole impressionante, il suo unico occhio scruta i dintorni in maniera frenetica alla ricerca di cibo. Nessun banchetto può saziare la sua fame e nessun combattimento può allietare la sua sete di sangue, la sua peggior caratteristica però resta la furia cieca inarrestabile che sfoga su qualunque cosa capiti a tiro. Le leggende dicono che la sua mazza chiodata sia composta dalle ossa dei nemici più valorosi che ha sconfitto.' },
    'monster-31': {id: 'monster-31', type: 'magical', label:	'Scheletro Irato'	, image:	scheletro_arciere, description: 'Mucchio d’ossa particolarmente suscettibile, un attaccabrighe. Usa spaventare i visitatori quando si avvicinano alla sua tomba e spesso ne causa la morte, come arma usa un arco fatto con una confusa accozzaglia di ossicini. Non può allontanarsi dalla tomba da cui è emerso perché perderebbe subito le forze e tornerebbe cenere…' },
    'monster-32': {id: 'monster-32', type: 'magical', label:	'Spirito Inquieto'	, image:	spirito, description: 'Una presenza che desta ansia, lugubre e lamentosa. Lancia urla strazianti che stordiscono e riducono la capacità di tenersi in equilibrio. Si dice che la sua presenza nel regno sia dovuta ai peccati degli abitanti del regno e che nessuno possa affrontarlo e avere la meglio.' },
    'monster-33': {id: 'monster-33', type: 'boss', label:	'Spirito'	, image:	spirito, description: 'Anima in pena, senza speranza di redenzione. Passa le sue giornate a vagare senza meta, non rappresenta una reale minaccia per nessuno. Le uniche sue vittime sono gli avventurieri che, incrociandolo durante delle esplorazioni, muoiono di crepacuore o finiscono in qualche dirupo fuggendo.' },
    'boss-1'	: {id: 'boss-1', type:'boss', label:	'Re Bestia'	, image:	re_bestia, description: 'Un rude esemplare di uomo bestia, si distingue per mole ed appetito. È riuscito a guadagnarsi il rispetto di tutti i mostri della caverna semplicemente uccidendo chiunque osasse sfidarlo; accompagnato sempre dai suoi fedeli servitori mangia tutto il giorno senza mai saziarsi.' },
    'boss-2'	: {id: 'boss-2', type:'boss', label:	'Genitrice dei Folletti'	, image:	genitrice_dei_folletti, description: 'Una mostruosità ripugnante, grassa e maleodorante. Di gran lunga più grossa di qualsiasi folletto esista in giro, si dice sia l’unica femmina rimasta in vita e che la specie dipenda interamente da lei. Terrorizzata dalla civiltà che avanza si rifugia nelle foreste a Nord della città e ne esce solo per cercare cibo per i suoi piccoli.' },
    'boss-3'	: {id: 'boss-3', type:'boss', label:	'Uruk'	, image:	uruk, description: 'Ogre dall’aspetto minaccioso ed imponente. Abituato dall’infanzia a vivere nelle caverne senza luce sviluppa una vista molto acuta che gli dona la capacità di sferrare attacchi precisi e allo stesso tempo potenti; la sua enorme ascia bipenne è assetata di sangue e la usa solo quando ritiene il nemico all’altezza della sfida.' },
    'boss-4'	: {id: 'boss-4', type:'boss', label:	'Goliath'	, image:	goliath, description: 'Gigante muscoloso e pieno di cicatrici, inquietante il suo grande occhio nero. Non si allontana mai dalla sua grotta perché lo smeraldo gli conferisce una forza sovrumana, le leggende infatti narrano che sia capace di uccidere un uomo con la sola forza di un dito della mano. Si dice mangi le sue vittime mentre sono ancora vive.' },
    'boss-5'	: {id: 'boss-5', type:'boss', label:	'Muro d\'ossa'	, image:	muro_d_ossa, description: 'All’apparenza un ammasso di ossa e crani senza fine. Formatosi nel corso dei secoli con tutti i resti di coloro che non hanno ricevuto una degna sepoltura, cova una fortissima rabbia verso il mondo dei vivi. Nei suoi piani c’è l’oscura intenzione di organizzare la rivolta dei non-morti ma non può allontanarsi dal Cimitero perché è da esso che trae le sue energie.' },
    'boss-6'	: {id: 'boss-6', type:'boss', label:	'Sarith'	, image:	sarith, description: 'Stregone dalle sembianze di un alto lupo, elegante e sfinato. La sua esistenza non è mai stata provata poiché nessuno fino ad ora aveva fatto ritorno dopo averlo incontrato. È così potente che decide di nascondere nella sua cripta i pezzi dell’unica arma che può annientarlo: una reliquia che mai nessuno è stato capace di ricostruire.' },
    'boss-7'	: {id: 'boss-7', type:'boss', label:	'Chimera Illusionista'	, image:	chimera_illusionista, description: 'Creatura misteriosa, schiva e senza tempo. Appare nei sogni degli uomini per rubare loro la serenità durante il sonno e si diverte a terrorizzare i visitatori del monastero facendo uso del suo speciale dono dell’ubiquità. Non esiste una stima della sua età, si dice abbia vissuto così a lungo da vedere i primi esseri umani colonizzare il regno.' },
    'boss-8'	: {id: 'boss-8', type:'boss', label:	'Nameless'	, image:	nameless, description: 'Presenza demoniaca dall’aura terrificante. La sua voce sembra provenire dall’aldilà, infatti si dice che sia la somma delle voci di tutti coloro che ha ucciso. Dotato di lunghi ed affilati artigli che usa come fossero lame, non perdona nessun intruso nella sua tana uccidendolo e divorando la sua anima.' },
    'boss-9'	: {id: 'boss-9', type:'boss', label:	'Ragno Titanico'	, image:	ragno_titanico, description: 'Una enorme bestia pelosa, con più occhi di quanti se ne possano contare con due mani. Da sempre celato nelle foreste non si cura di disturbare la zona civilizzata del regno perché non vuole seccature; quando si muove genera lunghi terremoti che distruggono qualunque cosa nel raggio di centinaia di metri.' },
    'boss-10'	: {id: 'boss-10', type:'boss', label:	'Cuore del Ragno'	, image:	cuore_del_ragno, description: 'Deforme, viscido ed incredibilmente grande. L’organo vitale del ragno titanico è di gran lunga la cosa più spaventosa e allo stesso tempo affascinante che gli eroi abbiano mai visto. Non sembra avere alcun punto debole: un rivestimento coriaceo lo riveste completamente e le lame più affilate finiscono per scalfirsi.' },
    'boss-11'	: {id: 'boss-11', type:'boss', label:	'Idra Regina'	, image:	idra_regina, description: 'Nota creatura che si nutre del terrore dei cittadini. In passato era libera di mangiare e spaventare tutti coloro che desiderava; le storie narrano però di un gruppo di eroi che la sconfiggono in battaglia costringendola alla ritirata in una prigione abbandonata e persa nell’oblio. Nei meandri degli umidi ambienti delle celle studia un piano per tornare allo scoperto e vendicarsi del torto subìto.' },
    'boss-12'	: {id: 'boss-12', type:'boss', label:	'Grendel degli Abissi'	, image:	grendel_degli_abissi, description: 'Esile figura dall’agilità notevole, feroce ed assetata di sangue. Nel branco da cui proviene vige la legge del più forte, il suo istinto di primeggiare gli ha consentito di esserne il leader. Cresciuto nell’oscurità e forgiato dalle tenebre escogita torture orribili per far sì che la sua vittima soffra il più possibile prima di morire: nei villaggi del regno quando si vuole augurare del male a qualcuno si dice “ti auguro di essere la prossima vittima del Grendel degli abissi”.' },
    'boss-13'	: {id: 'boss-13', type:'boss', label:	'Grendel degli Abissi (2° incontro)'	, image:	grendel_degli_abissi, description: 'La belva è ancor più feroce ed assetata della prima volta. La sconfitta nella sua mente non è contemplata, non dorme dal vostro primo incontro ed ha gli occhi iniettati di sangue. La sua sopravvivenza dipende solo da questo scontro, tornare nel branco da sconfitto sarebbe un disonore che non gli consentirebbe di tenerne la leadership: è disperato e disposto a tutto per raggiungere il suo scopo.' },
    'boss-14'	: {id: 'boss-14', type:'boss', label:	'Drago Millenario'	, image:	drago_millenario, description: 'Maestosa creatura senza tempo, orgogliosa e terrificante. Il suo aspetto è meraviglioso, si capisce perché tutte le creature che avete sconfitto hanno deciso di seguirlo. Le sue ampie ali possono spazzar via interi villaggi, la coda è un flagello che distrugge qualunque cosa incontri e il suo fiato infuocato è più caldo della lava. Nessuna delle leggende che narrano la sua magnificenza gli rende giustizia, mai nessuno è stato in grado di riportarne le fattezze dato che non esiste essere vivente sopravvissuto ad un incontro ravvicinato.' },
    'boss-15'	: {id: 'boss-15', type:'boss', label:	'Gusadt&Terodn'	, image:	gusadt_terodn, description: 'Due antipatici goblin determinati a far fuori quanti più abitanti possibile. Fratelli gemelli abbandonati pochi giorni dopo la loro nascita, sviluppano una fiducia reciproca che li rende praticamente un individuo solo. Il loro godimento sta nel veder soffrire i loro prigionieri: durante le notti senza Luna si recano nei villaggi dormienti e rapiscono casualmente degli abitanti per poi lasciarli morire di stenti.' },
    'boss-16'	: {id: 'boss-16', type:'boss', label:	'Garkar'	, image:	garkar, description: 'Un grosso esemplare di Minotauro, infuriato e privo di ogni controllo. Le sue lunghe corna sono un’arma micidiale e non si fa scrupoli ad usarle per infilzare chiunque gli si pari davanti. Dal momento in cui è apparso il bestiame nelle fattorie scompare senza lasciare traccia, si dice infatti che abbia un appetito insaziabile.' },
    'boss-17'	: {id: 'boss-17', type:'boss', label:	'Hurian'	, image:	hurian, description: 'Spettro senza volto, misterioso e cupo come la notte. Le sue apparizioni sono testimoniate da racconti e storie vecchie di secoli, nella mano destra ha un pugnale dalla lama ondulata con cui uccide le sue vittime e nella sinistra ha un globo maligno in cui ne imprigiona le anime. Guardando attraverso la sua sagoma ogni essere vivente osserva le proprie paure più grandi, come fosse un monito dei propri incubi.' },
    'boss-18'	: {id: 'boss-18', type:'boss', label:	'Nar\'Xarn'	, image:	nar_xarn, description: 'Demone dai tratti femminili, magra e spigolosa. La sua abilità consiste nel poter leggere la mente degli uomini, individuare le figure a cui questi tengono maggiormente e di assumerne le fattezze. Quando una persona all’apparenza docile si comporta in maniera irascibile si dice sia stata in realtà uccisa e sostituita dal demone Nar’Xarn, in pratica nessuno conosce il suo aspetto reale.' },
    'boss-19'	: {id: 'boss-19', type:'boss', label:	'Khun'	, image:	khun, description: 'Un Behemoth dalla pelle coriacea, aggressivo e arrogante. La sua pelle sembra carapace, di un colore simile alla corteccia d’ebano. I suoi tre occhi rossi incutono enorme terrore e possono scrutare i minimi particolare anche ad enormi distanze: tentare di sorprendere questa bestia è praticamente uno sforzo vano. Le leggende su di esso narrano che non si trattiene mai in un posto per molto tempo: vaga alla ricerca di avversari da sconfiggere e se non ne trova distrugge tutto ciò che incontra.' },
    'boss-20'	: {id: 'boss-20', type:'boss', label:	'Yarangur'	, image:	yarangur, description: 'Dragone proveniente dall’aldilà, composto da sole ossa e malvagità. È certamente la creatura più inquietante che abbiate mai visto, si nutre delle anime dannate e raramente visita il mondo dei vivi. Dal momento in cui è apparso tutti i cimiteri si animano di scheletri che terrorizzano i cittadini del regno, rubando loro i sogni e la tranquillità. Nessuna storia ne parla: è una creatura più antica delle storie stesse e non conosce la paura poiché la morte è il suo regno.' },
  },
  dungeons:{
    'dungeon-1': { id: 'dungeon-1', label: 'Caverna di Roth', fasce: ['fascia-1','fascia-2']},
    'dungeon-2': { id: 'dungeon-2', label: 'Foresta settentrionale', fasce: ['fascia-3','fascia-4']},
    'dungeon-3': { id: 'dungeon-3', label: 'Caverna buia', fasce: ['fascia-5','fascia-6']},
    'dungeon-4': { id: 'dungeon-4', label: 'Grotte di smeraldo', fasce: ['fascia-7','fascia-8']},
    'dungeon-5': { id: 'dungeon-5', label: 'Cimitero di Evreschi', fasce: ['fascia-9','fascia-10']},
    'dungeon-6': { id: 'dungeon-6', label: 'Cripta dello sconforto', fasce: ['fascia-11','fascia-12']},
    'dungeon-7': { id: 'dungeon-7', label: 'Monastero abbandonato', fasce: ['fascia-13','fascia-14']},
    'dungeon-8': { id: 'dungeon-8', label: 'Tana senza nome', fasce: ['fascia-15','fascia-16']},
    'dungeon-9': { id: 'dungeon-9', label: 'Altopiano ad ovest', fasce: ['fascia-17','fascia-18']},
    'dungeon-10': { id: 'dungeon-10', label: 'Ventre del ragno', fasce: ['fascia-19','fascia-20']},
    'dungeon-11': { id: 'dungeon-11', label: 'Prigione sotterranea', fasce: ['fascia-21','fascia-22']},
    'dungeon-12': { id: 'dungeon-12', label: 'Crepaccio antico', fasce: ['fascia-23','fascia-24','fascia-25']},
    'caccia-1'	: {id: 'caccia-1', label: 'Caccia 1', fasce: ['fascia-c1']},
    'caccia-2'	: {id: 'caccia-2', label: 'Caccia 2', fasce: ['fascia-c2']},
    'caccia-3'	: {id: 'caccia-3', label: 'Caccia 3', fasce: ['fascia-c3']},
    'caccia-4'	: {id: 'caccia-4', label: 'Caccia 4', fasce: ['fascia-c4']},
    'caccia-5'	: {id: 'caccia-5', label: 'Caccia 5', fasce: ['fascia-c5']},
    'caccia-6'	: {id: 'caccia-6', label: 'Caccia 6', fasce: ['fascia-c6']},
  },
  fasce:{
    'fascia-1'	: {id:'fascia-1', 	 levels: [	1	,	4	],	multipliers: [1],	 monsters: {	'monster-1'	 : {pv:	6	, def:	0	},	'monster-2'	 : {pv:	8	, def:	1	},	'monster-3'	 : {pv:	7	, def:	1	},	'monster-4'	 : {pv:	5	, def:	0	},	'monster-5'	 : {pv:	5	, def:	0	},	'monster-6'	 : {pv:	3	, def:	0	},	'monster-7'	 : {pv:	8	, def:	1	},	'monster-8'	 : {pv:	7	, def:	0	},	'monster-9'	 : {pv:	8	, def:	1	},	'boss-1'	 : {pv:	100	, def:	3	},	}},
    'fascia-2'	: {id:'fascia-2', 	 levels: [	5	,	8	],	multipliers: [2],	 monsters: {	'monster-1'	 : {pv:	8	, def:	1	},	'monster-2'	 : {pv:	12	, def:	1	},	'monster-3'	 : {pv:	10	, def:	1	},	'monster-4'	 : {pv:	7	, def:	1	},	'monster-5'	 : {pv:	7	, def:	0	},	'monster-6'	 : {pv:	5	, def:	0	},	'monster-7'	 : {pv:	10	, def:	1	},	'monster-8'	 : {pv:	9	, def:	1	},	'monster-9'	 : {pv:	10	, def:	1	},	'boss-1'	 : {pv:	100	, def:	3	},	}},
    'fascia-3'	: {id:'fascia-3', 	 levels: [	9	,	12	],	multipliers: [2],	 monsters: {	'monster-1'	 : {pv:	9	, def:	1	},	'monster-2'	 : {pv:	14	, def:	2	},	'monster-3'	 : {pv:	12	, def:	1	},	'monster-4'	 : {pv:	9	, def:	1	},	'monster-5'	 : {pv:	9	, def:	0	},	'monster-6'	 : {pv:	6	, def:	0	},	'monster-7'	 : {pv:	13	, def:	2	},	'monster-8'	 : {pv:	12	, def:	2	},	'monster-9'	 : {pv:	13	, def:	2	},	'boss-2'	 : {pv:	180	, def:	5	},	}},
    'fascia-4'	: {id:'fascia-4', 	 levels: [	13	,	16	],	multipliers: [3],	 monsters: {	'monster-1'	 : {pv:	13	, def:	2	},	'monster-2'	 : {pv:	19	, def:	2	},	'monster-3'	 : {pv:	15	, def:	2	},	'monster-4'	 : {pv:	12	, def:	1	},	'monster-5'	 : {pv:	12	, def:	1	},	'monster-6'	 : {pv:	8	, def:	0	},	'monster-7'	 : {pv:	18	, def:	3	},	'monster-8'	 : {pv:	16	, def:	2	},	'monster-9'	 : {pv:	18	, def:	2	},	'boss-2'	 : {pv:	180	, def:	5	},	}},
    'fascia-5'	: {id:'fascia-5', 	 levels: [	17	,	20	],	multipliers: [3],	 monsters: {	'monster-1'	 : {pv:	15	, def:	2	},	'monster-2'	 : {pv:	22	, def:	2	},	'monster-3'	 : {pv:	18	, def:	2	},	'monster-4'	 : {pv:	15	, def:	2	},	'monster-5'	 : {pv:	15	, def:	2	},	'monster-6'	 : {pv:	9	, def:	0	},	'monster-7'	 : {pv:	20	, def:	3	},	'monster-8'	 : {pv:	18	, def:	3	},	'monster-9'	 : {pv:	20	, def:	3	},	'monster-10'	 : {pv:	33	, def:	3	},	'monster-11'	 : {pv:	32	, def:	3	},	'monster-12'	 : {pv:	28	, def:	2	},	'monster-13'	 : {pv:	27	, def:	2	},	'monster-14'	 : {pv:	28	, def:	2	},	'monster-15'	 : {pv:	28	, def:	2	},	'monster-16'	 : {pv:	35	, def:	3	},	'monster-17'	 : {pv:	29	, def:	2	},	'monster-18'	 : {pv:	34	, def:	3	},	'boss-3'	 : {pv:	250	, def:	8	},	}},
    'fascia-6'	: {id:'fascia-6', 	 levels: [	21	,	24	],	multipliers: [3],	 monsters: {	'monster-1'	 : {pv:	22	, def:	3	},	'monster-2'	 : {pv:	28	, def:	3	},	'monster-3'	 : {pv:	26	, def:	2	},	'monster-4'	 : {pv:	25	, def:	2	},	'monster-5'	 : {pv:	25	, def:	2	},	'monster-6'	 : {pv:	12	, def:	0	},	'monster-7'	 : {pv:	27	, def:	4	},	'monster-8'	 : {pv:	26	, def:	3	},	'monster-9'	 : {pv:	27	, def:	4	},	'monster-10'	 : {pv:	39	, def:	3	},	'monster-11'	 : {pv:	38	, def:	4	},	'monster-12'	 : {pv:	32	, def:	2	},	'monster-13'	 : {pv:	31	, def:	2	},	'monster-14'	 : {pv:	32	, def:	2	},	'monster-15'	 : {pv:	32	, def:	2	},	'monster-16'	 : {pv:	41	, def:	3	},	'monster-17'	 : {pv:	34	, def:	2	},	'monster-18'	 : {pv:	40	, def:	4	},	'boss-3'	 : {pv:	250	, def:	8	},	}},
    'fascia-7'	: {id:'fascia-7', 	 levels: [	25	,	28	],	multipliers: [4],	 monsters: {	'monster-1'	 : {pv:	25	, def:	3	},	'monster-2'	 : {pv:	34	, def:	3	},	'monster-3'	 : {pv:	30	, def:	2	},	'monster-4'	 : {pv:	28	, def:	2	},	'monster-5'	 : {pv:	28	, def:	2	},	'monster-6'	 : {pv:	15	, def:	0	},	'monster-7'	 : {pv:	30	, def:	4	},	'monster-8'	 : {pv:	29	, def:	3	},	'monster-9'	 : {pv:	30	, def:	4	},	'monster-10'	 : {pv:	46	, def:	4	},	'monster-11'	 : {pv:	44	, def:	4	},	'monster-12'	 : {pv:	38	, def:	2	},	'monster-13'	 : {pv:	37	, def:	2	},	'monster-14'	 : {pv:	38	, def:	3	},	'monster-15'	 : {pv:	38	, def:	3	},	'monster-16'	 : {pv:	48	, def:	4	},	'monster-17'	 : {pv:	40	, def:	3	},	'monster-18'	 : {pv:	47	, def:	4	},	'boss-4'	 : {pv:	450	, def:	9	},	}},
    'fascia-8'	: {id:'fascia-8', 	 levels: [	29	,	32	],	multipliers: [4],	 monsters: {	'monster-1'	 : {pv:	28	, def:	3	},	'monster-2'	 : {pv:	38	, def:	3	},	'monster-3'	 : {pv:	33	, def:	3	},	'monster-4'	 : {pv:	31	, def:	2	},	'monster-5'	 : {pv:	31	, def:	2	},	'monster-6'	 : {pv:	17	, def:	0	},	'monster-7'	 : {pv:	34	, def:	5	},	'monster-8'	 : {pv:	32	, def:	3	},	'monster-9'	 : {pv:	33	, def:	4	},	'monster-10'	 : {pv:	50	, def:	4	},	'monster-11'	 : {pv:	48	, def:	4	},	'monster-12'	 : {pv:	42	, def:	3	},	'monster-13'	 : {pv:	41	, def:	3	},	'monster-14'	 : {pv:	42	, def:	3	},	'monster-15'	 : {pv:	42	, def:	3	},	'monster-16'	 : {pv:	53	, def:	4	},	'monster-17'	 : {pv:	44	, def:	3	},	'monster-18'	 : {pv:	51	, def:	5	},	'boss-4'	 : {pv:	450	, def:	9	},	}},
    'fascia-9'	: {id:'fascia-9', 	 levels: [	33	,	36	],	multipliers: [5],	 monsters: {	'monster-1'	 : {pv:	31	, def:	3	},	'monster-2'	 : {pv:	41	, def:	4	},	'monster-3'	 : {pv:	36	, def:	4	},	'monster-4'	 : {pv:	33	, def:	2	},	'monster-5'	 : {pv:	33	, def:	2	},	'monster-6'	 : {pv:	18	, def:	0	},	'monster-7'	 : {pv:	37	, def:	5	},	'monster-8'	 : {pv:	35	, def:	4	},	'monster-9'	 : {pv:	36	, def:	5	},	'monster-10'	 : {pv:	54	, def:	5	},	'monster-11'	 : {pv:	52	, def:	6	},	'monster-12'	 : {pv:	45	, def:	3	},	'monster-13'	 : {pv:	44	, def:	4	},	'monster-14'	 : {pv:	45	, def:	4	},	'monster-15'	 : {pv:	45	, def:	3	},	'monster-16'	 : {pv:	57	, def:	5	},	'monster-17'	 : {pv:	47	, def:	3	},	'monster-18'	 : {pv:	55	, def:	6	},	'monster-31'	 : {pv:	150	, def:	8	}, 	'boss-5'	 : {pv:	700	, def:	10	},	}},
    'fascia-10'	: {id:'fascia-10', 	 levels: [	37	,	40	],	multipliers: [5],	 monsters: {	'monster-1'	 : {pv:	34	, def:	4	},	'monster-2'	 : {pv:	45	, def:	5	},	'monster-3'	 : {pv:	39	, def:	4	},	'monster-4'	 : {pv:	35	, def:	3	},	'monster-5'	 : {pv:	35	, def:	3	},	'monster-6'	 : {pv:	19	, def:	0	},	'monster-7'	 : {pv:	41	, def:	6	},	'monster-8'	 : {pv:	38	, def:	5	},	'monster-9'	 : {pv:	39	, def:	6	},	'monster-10'	 : {pv:	58	, def:	6	},	'monster-11'	 : {pv:	56	, def:	6	},	'monster-12'	 : {pv:	49	, def:	3	},	'monster-13'	 : {pv:	48	, def:	4	},	'monster-14'	 : {pv:	49	, def:	4	},	'monster-15'	 : {pv:	49	, def:	3	},	'monster-16'	 : {pv:	62	, def:	6	},	'monster-17'	 : {pv:	51	, def:	3	},	'monster-18'	 : {pv:	60	, def:	6	},	'monster-31'	 : {pv:	150	, def:	8	},	'boss-5'	 : {pv:	700	, def:	10	},	}},
    'fascia-11'	: {id:'fascia-11', 	 levels: [	41	,	44	],	multipliers: [5,6],	 monsters: {	'monster-10'	 : {pv:	64	, def:	6	},	'monster-11'	 : {pv:	61	, def:	7	},	'monster-12'	 : {pv:	54	, def:	4	},	'monster-13'	 : {pv:	53	, def:	5	},	'monster-14'	 : {pv:	54	, def:	5	},	'monster-15'	 : {pv:	54	, def:	4	},	'monster-16'	 : {pv:	68	, def:	7	},	'monster-17'	 : {pv:	56	, def:	4	},	'monster-18'	 : {pv:	66	, def:	7	},	'monster-19'	 : {pv:	90	, def:	7	},	'monster-20'	 : {pv:	97	, def:	8	},	'monster-21'	 : {pv:	94	, def:	8	},	'monster-22'	 : {pv:	100	, def:	10	},	'monster-23'	 : {pv:	110	, def:	11	},	'monster-24'	 : {pv:	85	, def:	6	},	'monster-25'	 : {pv:	100	, def:	8	},	'monster-26'	 : {pv:	104	, def:	8	},	'monster-27'	 : {pv:	102	, def:	9	},	'monster-32'	 : {pv:	100	, def:	0	},	'monster-33'	 : {pv:	19	, def:	0	},	'boss-6'	 : {pv:	450	, def:	8	},	}},
    'fascia-12'	: {id:'fascia-12', 	 levels: [	45	,	48	],	multipliers: [5,6],	 monsters: {	'monster-10'	 : {pv:	69	, def:	6	},	'monster-11'	 : {pv:	66	, def:	7	},	'monster-12'	 : {pv:	59	, def:	4	},	'monster-13'	 : {pv:	58	, def:	5	},	'monster-14'	 : {pv:	59	, def:	5	},	'monster-15'	 : {pv:	59	, def:	4	},	'monster-16'	 : {pv:	73	, def:	8	},	'monster-17'	 : {pv:	61	, def:	4	},	'monster-18'	 : {pv:	70	, def:	7	},	'monster-19'	 : {pv:	96	, def:	8	},	'monster-20'	 : {pv:	104	, def:	8	},	'monster-21'	 : {pv:	101	, def:	8	},	'monster-22'	 : {pv:	107	, def:	11	},	'monster-23'	 : {pv:	118	, def:	13	},	'monster-24'	 : {pv:	90	, def:	6	},	'monster-25'	 : {pv:	107	, def:	9	},	'monster-26'	 : {pv:	111	, def:	9	},	'monster-27'	 : {pv:	109	, def:	10	},	'monster-32'	 : {pv:	100	, def:	0	},	'monster-33'	 : {pv:	19	, def:	0	},	'boss-6'	 : {pv:	450	, def:	8	},	}},
    'fascia-13'	: {id:'fascia-13', 	 levels: [	49	,	52	],	multipliers: [6],	 monsters: {	'monster-10'	 : {pv:	75	, def:	7	},	'monster-11'	 : {pv:	72	, def:	7	},	'monster-12'	 : {pv:	64	, def:	5	},	'monster-13'	 : {pv:	63	, def:	5	},	'monster-14'	 : {pv:	64	, def:	5	},	'monster-15'	 : {pv:	64	, def:	5	},	'monster-16'	 : {pv:	79	, def:	7	},	'monster-17'	 : {pv:	65	, def:	5	},	'monster-18'	 : {pv:	76	, def:	7	},	'monster-19'	 : {pv:	103	, def:	9	},	'monster-20'	 : {pv:	111	, def:	9	},	'monster-21'	 : {pv:	108	, def:	9	},	'monster-22'	 : {pv:	115	, def:	12	},	'monster-23'	 : {pv:	127	, def:	14	},	'monster-24'	 : {pv:	97	, def:	7	},	'monster-25'	 : {pv:	115	, def:	10	},	'monster-26'	 : {pv:	119	, def:	10	},	'monster-27'	 : {pv:	117	, def:	11	},	'boss-7'	 : {pv:	900	, def:	20	},	}},
    'fascia-14'	: {id:'fascia-14', 	 levels: [	53	,	56	],	multipliers: [6],	 monsters: {	'monster-10'	 : {pv:	82	, def:	7	},	'monster-11'	 : {pv:	79	, def:	7	},	'monster-12'	 : {pv:	70	, def:	5	},	'monster-13'	 : {pv:	69	, def:	5	},	'monster-14'	 : {pv:	70	, def:	6	},	'monster-15'	 : {pv:	70	, def:	5	},	'monster-16'	 : {pv:	86	, def:	8	},	'monster-17'	 : {pv:	71	, def:	5	},	'monster-18'	 : {pv:	83	, def:	8	},	'monster-19'	 : {pv:	110	, def:	10	},	'monster-20'	 : {pv:	119	, def:	10	},	'monster-21'	 : {pv:	116	, def:	10	},	'monster-22'	 : {pv:	123	, def:	13	},	'monster-23'	 : {pv:	135	, def:	15	},	'monster-24'	 : {pv:	104	, def:	7	},	'monster-25'	 : {pv:	123	, def:	11	},	'monster-26'	 : {pv:	127	, def:	11	},	'monster-27'	 : {pv:	125	, def:	12	},	'boss-7'	 : {pv:	900	, def:	20	},	}},
    'fascia-15'	: {id:'fascia-15', 	 levels: [	57	,	60	],	multipliers: [7],	 monsters: {	'monster-10'	 : {pv:	90	, def:	7	},	'monster-11'	 : {pv:	87	, def:	8	},	'monster-12'	 : {pv:	77	, def:	5	},	'monster-13'	 : {pv:	76	, def:	6	},	'monster-14'	 : {pv:	77	, def:	6	},	'monster-15'	 : {pv:	77	, def:	6	},	'monster-16'	 : {pv:	94	, def:	8	},	'monster-17'	 : {pv:	78	, def:	6	},	'monster-18'	 : {pv:	91	, def:	8	},	'monster-19'	 : {pv:	118	, def:	11	},	'monster-20'	 : {pv:	128	, def:	11	},	'monster-21'	 : {pv:	124	, def:	11	},	'monster-22'	 : {pv:	132	, def:	14	},	'monster-23'	 : {pv:	145	, def:	17	},	'monster-24'	 : {pv:	112	, def:	8	},	'monster-25'	 : {pv:	132	, def:	12	},	'monster-26'	 : {pv:	136	, def:	12	},	'monster-27'	 : {pv:	134	, def:	13	},	'boss-8'	 : {pv:	1000	, def:	16	},	}},
    'fascia-16'	: {id:'fascia-16', 	 levels: [	61	,	64	],	multipliers: [7],	 monsters: {	'monster-10'	 : {pv:	98	, def:	8	},	'monster-11'	 : {pv:	96	, def:	8	},	'monster-12'	 : {pv:	85	, def:	5	},	'monster-13'	 : {pv:	84	, def:	6	},	'monster-14'	 : {pv:	85	, def:	7	},	'monster-15'	 : {pv:	85	, def:	6	},	'monster-16'	 : {pv:	104	, def:	9	},	'monster-17'	 : {pv:	87	, def:	7	},	'monster-18'	 : {pv:	100	, def:	9	},	'monster-19'	 : {pv:	126	, def:	12	},	'monster-20'	 : {pv:	137	, def:	12	},	'monster-21'	 : {pv:	132	, def:	12	},	'monster-22'	 : {pv:	141	, def:	15	},	'monster-23'	 : {pv:	155	, def:	19	},	'monster-24'	 : {pv:	120	, def:	9	},	'monster-25'	 : {pv:	141	, def:	13	},	'monster-26'	 : {pv:	145	, def:	13	},	'monster-27'	 : {pv:	142	, def:	14	},	'boss-8'	 : {pv:	1000	, def:	16	},	}},
    'fascia-17'	: {id:'fascia-17', 	 levels: [	65	,	68	],	multipliers: [7],	 monsters: {	'monster-10'	 : {pv:	98	, def:	8	},	'monster-11'	 : {pv:	96	, def:	8	},	'monster-12'	 : {pv:	85	, def:	5	},	'monster-13'	 : {pv:	84	, def:	6	},	'monster-14'	 : {pv:	85	, def:	7	},	'monster-15'	 : {pv:	85	, def:	6	},	'monster-16'	 : {pv:	104	, def:	9	},	'monster-17'	 : {pv:	87	, def:	7	},	'monster-18'	 : {pv:	100	, def:	9	},	'monster-19'	 : {pv:	135	, def:	13	},	'monster-20'	 : {pv:	147	, def:	13	},	'monster-21'	 : {pv:	141	, def:	13	},	'monster-22'	 : {pv:	151	, def:	16	},	'monster-23'	 : {pv:	166	, def:	21	},	'monster-24'	 : {pv:	128	, def:	9	},	'monster-25'	 : {pv:	151	, def:	14	},	'monster-26'	 : {pv:	155	, def:	14	},	'monster-27'	 : {pv:	152	, def:	15	},	'boss-9'	 : {pv:	1250	, def:	1	},	}},
    'fascia-18'	: {id:'fascia-18', 	 levels: [	69	,	72	],	multipliers: [7],	 monsters: {	'monster-10'	 : {pv:	98	, def:	8	},	'monster-11'	 : {pv:	96	, def:	8	},	'monster-12'	 : {pv:	85	, def:	5	},	'monster-13'	 : {pv:	84	, def:	6	},	'monster-14'	 : {pv:	85	, def:	7	},	'monster-15'	 : {pv:	85	, def:	6	},	'monster-16'	 : {pv:	104	, def:	9	},	'monster-17'	 : {pv:	87	, def:	7	},	'monster-18'	 : {pv:	100	, def:	9	},	'monster-19'	 : {pv:	144	, def:	13	},	'monster-20'	 : {pv:	157	, def:	14	},	'monster-21'	 : {pv:	150	, def:	14	},	'monster-22'	 : {pv:	161	, def:	17	},	'monster-23'	 : {pv:	177	, def:	23	},	'monster-24'	 : {pv:	137	, def:	9	},	'monster-25'	 : {pv:	161	, def:	15	},	'monster-26'	 : {pv:	165	, def:	15	},	'monster-27'	 : {pv:	162	, def:	15	},	'boss-9'	 : {pv:	1250	, def:	1	},	}},
    'fascia-19'	: {id:'fascia-19', 	 levels: [	73	,	76	],	multipliers: [8],	 monsters: {	'monster-19'	 : {pv:	154	, def:	13	},	'monster-20'	 : {pv:	168	, def:	15	},	'monster-21'	 : {pv:	160	, def:	15	},	'monster-22'	 : {pv:	172	, def:	18	},	'monster-23'	 : {pv:	190	, def:	25	},	'monster-24'	 : {pv:	146	, def:	10	},	'monster-25'	 : {pv:	172	, def:	16	},	'monster-26'	 : {pv:	177	, def:	16	},	'monster-27'	 : {pv:	173	, def:	16	},	'monster-28'	 : {pv:	750	, def:	30	},	'monster-29'	 : {pv:	500	, def:	18	},	'monster-30'	 : {pv:	600	, def:	22	},	'boss-10'	 : {pv:	2500	, def:	30	},	}},
    'fascia-20'	: {id:'fascia-20', 	 levels: [	77	,	80	],	multipliers: [8],	 monsters: {	'monster-19'	 : {pv:	165	, def:	14	},	'monster-20'	 : {pv:	180	, def:	16	},	'monster-21'	 : {pv:	170	, def:	16	},	'monster-22'	 : {pv:	185	, def:	19	},	'monster-23'	 : {pv:	205	, def:	27	},	'monster-24'	 : {pv:	155	, def:	11	},	'monster-25'	 : {pv:	185	, def:	17	},	'monster-26'	 : {pv:	190	, def:	17	},	'monster-27'	 : {pv:	185	, def:	17	},	'monster-28'	 : {pv:	850	, def:	35	},	'monster-29'	 : {pv:	600	, def:	23	},	'monster-30'	 : {pv:	700	, def:	27	},	'boss-10'	 : {pv:	2500	, def:	30	},	}},
    'fascia-21'	: {id:'fascia-21', 	 levels: [	81	,	84	],	multipliers: [9],	 monsters: {	'monster-19'	 : {pv:	165	, def:	14	},	'monster-20'	 : {pv:	180	, def:	16	},	'monster-21'	 : {pv:	170	, def:	16	},	'monster-22'	 : {pv:	185	, def:	19	},	'monster-23'	 : {pv:	205	, def:	27	},	'monster-24'	 : {pv:	155	, def:	11	},	'monster-25'	 : {pv:	185	, def:	17	},	'monster-26'	 : {pv:	190	, def:	17	},	'monster-27'	 : {pv:	185	, def:	17	},	'monster-28'	 : {pv:	950	, def:	40	},	'monster-29'	 : {pv:	700	, def:	27	},	'monster-30'	 : {pv:	800	, def:	32	},	'boss-11'	 : {pv:	1300	, def:	30	},	'boss-12'	 : {pv:	2000	, def:	18	},	}},
    'fascia-22'	: {id:'fascia-22', 	 levels: [	85	,	88	],	multipliers: [9],	 monsters: {	'monster-19'	 : {pv:	165	, def:	14	},	'monster-20'	 : {pv:	180	, def:	16	},	'monster-21'	 : {pv:	170	, def:	16	},	'monster-22'	 : {pv:	185	, def:	19	},	'monster-23'	 : {pv:	205	, def:	27	},	'monster-24'	 : {pv:	155	, def:	11	},	'monster-25'	 : {pv:	185	, def:	17	},	'monster-26'	 : {pv:	190	, def:	17	},	'monster-27'	 : {pv:	185	, def:	17	},	'monster-28'	 : {pv:	1100	, def:	45	},	'monster-29'	 : {pv:	850	, def:	31	},	'monster-30'	 : {pv:	950	, def:	37	},	'boss-11'	 : {pv:	1300	, def:	30	},	'boss-12'	 : {pv:	2000	, def:	18	},	}},
    'fascia-23'	: {id:'fascia-23', 	 levels: [	89	,	92	],	multipliers: [9,10],	 monsters: {	'monster-19'	 : {pv:	165	, def:	14	},	'monster-20'	 : {pv:	180	, def:	16	},	'monster-21'	 : {pv:	170	, def:	16	},	'monster-22'	 : {pv:	185	, def:	19	},	'monster-23'	 : {pv:	205	, def:	27	},	'monster-24'	 : {pv:	155	, def:	11	},	'monster-25'	 : {pv:	185	, def:	17	},	'monster-26'	 : {pv:	190	, def:	17	},	'monster-27'	 : {pv:	185	, def:	17	},	'monster-28'	 : {pv:	1250	, def:	50	},	'monster-29'	 : {pv:	1000	, def:	35	},	'monster-30'	 : {pv:	1100	, def:	41	},	'boss-13'	 : {pv:	2500	, def:	20	},	'boss-14'	 : {pv:	3000	, def:	60	},	}},
    'fascia-24'	: {id:'fascia-24', 	 levels: [	93	,	96	],	multipliers: [9,10],	 monsters: {	'monster-19'	 : {pv:	165	, def:	14	},	'monster-20'	 : {pv:	180	, def:	16	},	'monster-21'	 : {pv:	170	, def:	16	},	'monster-22'	 : {pv:	185	, def:	19	},	'monster-23'	 : {pv:	205	, def:	27	},	'monster-24'	 : {pv:	155	, def:	11	},	'monster-25'	 : {pv:	185	, def:	17	},	'monster-26'	 : {pv:	190	, def:	17	},	'monster-27'	 : {pv:	185	, def:	17	},	'monster-28'	 : {pv:	1400	, def:	55	},	'monster-29'	 : {pv:	1150	, def:	40	},	'monster-30'	 : {pv:	1300	, def:	46	},	'boss-13'	 : {pv:	2500	, def:	20	},	'boss-14'	 : {pv:	3000	, def:	60	},	}},
    'fascia-25'	: {id:'fascia-25', 	 levels: [	97	,	100	],	multipliers: [9,10],	 monsters: {	'monster-19'	 : {pv:	165	, def:	14	},	'monster-20'	 : {pv:	180	, def:	16	},	'monster-21'	 : {pv:	170	, def:	16	},	'monster-22'	 : {pv:	185	, def:	19	},	'monster-23'	 : {pv:	205	, def:	27	},	'monster-24'	 : {pv:	155	, def:	11	},	'monster-25'	 : {pv:	185	, def:	17	},	'monster-26'	 : {pv:	190	, def:	17	},	'monster-27'	 : {pv:	185	, def:	17	},	'monster-28'	 : {pv:	1700	, def:	60	},	'monster-29'	 : {pv:	1300	, def:	45	},	'monster-30'	 : {pv:	1500	, def:	52	},	'boss-13'	 : {pv:	2500	, def:	20	},	'boss-14'	 : {pv:	3000	, def:	60	},	}},
    'fascia-c1'	: {id:'fascia-c1',	 levels: [	0	,	100	],	multipliers: [4],	 monsters: {	'boss-15'	 : {pv:	500	, def:	6	},	}},
    'fascia-c2'	: {id:'fascia-c2',	 levels: [	0	,	100	],	multipliers: [6],	 monsters: {	'boss-16'	 : {pv:	1000	, def:	15	},	}},
    'fascia-c3'	: {id:'fascia-c3',	 levels: [	0	,	100	],	multipliers: [8],	 monsters: {	'boss-17'	 : {pv:	1000	, def:	0	},	}},
    'fascia-c4'	: {id:'fascia-c4',	 levels: [	0	,	100	],	multipliers: [9],	 monsters: {	'boss-18'	 : {pv:	1500	, def:	16	},	}},
    'fascia-c5'	: {id:'fascia-c5',	 levels: [	0	,	100	],	multipliers: [10],	 monsters: {	'boss-19'	 : {pv:	3000	, def:	50	},	}},
    'fascia-c6'	: {id:'fascia-c6',	 levels: [	0	,	100	],	multipliers: [10],	 monsters: {	'boss-20'	 : {pv:	5000	, def:	70	},	}},


  },
  fasceIds: ['fascia-1','fascia-2','fascia-3','fascia-4','fascia-5','fascia-6','fascia-7','fascia-8','fascia-9','fascia-10','fascia-11','fascia-12','fascia-13','fascia-14','fascia-15','fascia-16','fascia-17','fascia-18','fascia-19','fascia-20','fascia-21','fascia-22','fascia-23','fascia-24','fascia-25','fascia-c1',	'fascia-c2',	'fascia-c3',	'fascia-c4',	'fascia-c5',	'fascia-c6',],
  monstersIds: ['monster-1',	'monster-2',	'monster-3',	'monster-4',	'monster-5',	'monster-6',	'monster-7',	'monster-8',	'monster-9',	'monster-10',	'monster-11',	'monster-12',	'monster-13',	'monster-14',	'monster-15',	'monster-16',	'monster-17',	'monster-18',	'monster-19',	'monster-20',	'monster-21',	'monster-22',	'monster-23',	'monster-24',	'monster-25',	'monster-26',	'monster-27',	'monster-28',	'monster-29',	'monster-30',	'monster-31',	'monster-32', 'monster-33', 'boss-1',	'boss-2',	'boss-3',	'boss-4',	'boss-5',	'boss-6',	'boss-7',	'boss-8',	'boss-9',	'boss-10',	'boss-11',	'boss-12',	'boss-13',	'boss-14',	'boss-15',	'boss-16',	'boss-17',	'boss-18',	'boss-19',	'boss-20',],
  dungeonsIds: ['dungeon-1',	'dungeon-2', 'dungeon-3', 'dungeon-4', 'dungeon-5', 'dungeon-6', 'dungeon-7', 'dungeon-8', 'dungeon-9', 'dungeon-10', 'dungeon-11', 'dungeon-12','caccia-1','caccia-2','caccia-3','caccia-4','caccia-5','caccia-6'],
}
export default monstersList;